name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Add conda to system path
      run: |
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base

    - name: Lint with flake8
      run: |
        conda install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        conda install pytest
        pytest

    - name: Install dependencies (pip)
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run contribute.py Script
      run: python src/contribute.py https://github.com/${{ github.repository }}

    - name: Make Script Executable
      run: chmod +x src/contribute.py
